name: All tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: oven-sh/setup-bun@v1

      - name: Build server-js
        run: |
          bun i
          make server-js

      - name: Test server-js
        run: |
          bun i
          make server-js/test

      - name: Build client
        run: |
          bun i
          make client
